# Generated by Django 3.2.5 on 2022-09-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrouselIntroduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='carrouselle_intro/%Y/%m/%d')),
                ('descripcion', models.CharField(blank=True, max_length=220, null=True, verbose_name='Descripcion (220)')),
                ('ir_a', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Introducción Carrouselle',
                'verbose_name_plural': 'Introducción Carrouselle',
            },
        ),
    ]
