# Generated by Django 3.2.5 on 2022-09-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrouselintroduccion',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo'),
        ),
    ]
